stages:
  - lint
  - test

default:
  image: rust:latest
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - .cargo/
      - target/

variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo
  CARGO_TERM_COLOR: always

lint:
  stage: lint
  before_script:
    - rustup component add rustfmt clippy
  script:
    - cargo fmt --all -- --check
    - cargo clippy --all-targets -- -D warnings

test:
  stage: test
  script:
    - cargo test --all
