stages:
  - test

variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo
  CARGO_TERM_COLOR: always

rust:
  stage: test
  image: rust:latest
  before_script:
    - rustup component add rustfmt clippy
  script:
    - cargo fmt --all -- --check
    - cargo clippy --all-targets -- -D warnings
    - cargo test --all
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - .cargo/
      - target/
